@ECHO OFF
ECHO ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
ECHO ³               Installation of MMC103 Systemsoftware                  ³
ECHO ³                               V4.4                                   ³
ECHO ³                                                                      ³
ECHO ³ WARNINGS:            PLEASE READ CAREFULLY !                         ³
ECHO ³          1. This Installation is ONLY(!) for MMC103-Hardware !!!     ³
ECHO ³          2. Dual-Boot (i.e. WFW 3.11 & P3.x) will be removed !!!     ³
ECHO ³          3. Userdata are kept (exept OLD version lower V4.2 !!!)     ³
ECHO ³                                                                      ³
ECHO ³ WARNUNGEN:           BITTE SORGFLTIG LESEN !                        ³
ECHO ³          1. Diese Installation ist NUR(!) fr MMC103-Hardware !!!    ³
ECHO ³          2. Dual-Boot (d.h. WFW 3.11 & SW P3.x) wird gel”scht !!!    ³
ECHO ³          3. Anwenderdaten bleiben erhalten                           ³
ECHO ³             (auáer ALTE Version kleiner V4.2 !!!)                    ³
ECHO ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
set free_space=14

